/*
  # Healthcare Assistance Platform Schema

  This migration creates the core database schema for an AI-powered healthcare assistance platform
  with emergency support, hospital finder, ambulance tracking, and AI chatbot features.

  ## New Tables

  ### 1. profiles
  - Stores user profile information extending auth.users
  - `id` (uuid, primary key, references auth.users)
  - `full_name` (text)
  - `phone` (text)
  - `blood_type` (text)
  - `date_of_birth` (date)
  - `address` (text)
  - `emergency_contact` (jsonb) - stores emergency contact information
  - `medical_conditions` (text[]) - array of medical conditions
  - `allergies` (text[]) - array of allergies
  - `current_medications` (text[]) - array of medications
  - `location_lat` (decimal) - user's last known latitude
  - `location_lng` (decimal) - user's last known longitude
  - `created_at`, `updated_at` (timestamps)

  ### 2. hospitals
  - Hospital information and locations
  - `id` (uuid, primary key)
  - `name` (text)
  - `address` (text)
  - `phone` (text)
  - `location_lat` (decimal)
  - `location_lng` (decimal)
  - `emergency_capacity` (integer) - number of emergency beds
  - `available_beds` (integer)
  - `specialties` (text[]) - cardiology, trauma, etc.
  - `accepts_emergency` (boolean)
  - `rating` (decimal)
  - `created_at`, `updated_at` (timestamps)

  ### 3. ambulances
  - Ambulance fleet information and tracking
  - `id` (uuid, primary key)
  - `vehicle_number` (text, unique)
  - `driver_name` (text)
  - `driver_phone` (text)
  - `location_lat` (decimal)
  - `location_lng` (decimal)
  - `status` (text) - available, busy, offline
  - `hospital_id` (uuid, references hospitals)
  - `created_at`, `updated_at` (timestamps)

  ### 4. emergency_requests
  - Emergency request tracking
  - `id` (uuid, primary key)
  - `user_id` (uuid, references auth.users)
  - `hospital_id` (uuid, references hospitals)
  - `ambulance_id` (uuid, references ambulances)
  - `status` (text) - pending, dispatched, en_route, arrived, completed, cancelled
  - `severity` (text) - low, medium, high, critical
  - `symptoms` (text[])
  - `description` (text)
  - `pickup_location` (jsonb) - {lat, lng, address}
  - `estimated_arrival` (timestamp)
  - `actual_arrival` (timestamp)
  - `created_at`, `updated_at` (timestamps)

  ### 5. chat_sessions
  - AI chatbot session tracking
  - `id` (uuid, primary key)
  - `user_id` (uuid, references auth.users)
  - `title` (text)
  - `status` (text) - active, closed
  - `created_at`, `updated_at` (timestamps)

  ### 6. chat_messages
  - Individual chat messages
  - `id` (uuid, primary key)
  - `session_id` (uuid, references chat_sessions)
  - `user_id` (uuid, references auth.users)
  - `role` (text) - user, assistant, system
  - `content` (text)
  - `metadata` (jsonb) - additional context
  - `created_at` (timestamp)

  ### 7. patient_vitals
  - Patient vital signs monitoring
  - `id` (uuid, primary key)
  - `user_id` (uuid, references auth.users)
  - `emergency_request_id` (uuid, references emergency_requests)
  - `heart_rate` (integer)
  - `blood_pressure` (text)
  - `temperature` (decimal)
  - `oxygen_level` (integer)
  - `respiratory_rate` (integer)
  - `notes` (text)
  - `recorded_at` (timestamp)

  ## Security

  - Row Level Security (RLS) enabled on all tables
  - Policies ensure users can only access their own data
  - Public read access for hospitals (available hospitals visible to all)
  - Public read access for ambulances status (for tracking)

  ## Important Notes

  1. All tables use uuid primary keys generated by gen_random_uuid()
  2. Timestamps use timestamptz for proper timezone handling
  3. JSONB columns for flexible data structures (emergency_contact, pickup_location, metadata)
  4. Array columns for lists (symptoms, specialties, medical_conditions, allergies, medications)
  5. Foreign key constraints ensure data integrity
*/

-- Enable UUID extension if not exists
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Profiles table (extends auth.users)
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text DEFAULT '',
  phone text DEFAULT '',
  blood_type text DEFAULT '',
  date_of_birth date,
  address text DEFAULT '',
  emergency_contact jsonb DEFAULT '{}'::jsonb,
  medical_conditions text[] DEFAULT ARRAY[]::text[],
  allergies text[] DEFAULT ARRAY[]::text[],
  current_medications text[] DEFAULT ARRAY[]::text[],
  location_lat decimal DEFAULT 0,
  location_lng decimal DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Hospitals table
CREATE TABLE IF NOT EXISTS hospitals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  address text NOT NULL,
  phone text DEFAULT '',
  location_lat decimal NOT NULL,
  location_lng decimal NOT NULL,
  emergency_capacity integer DEFAULT 10,
  available_beds integer DEFAULT 5,
  specialties text[] DEFAULT ARRAY[]::text[],
  accepts_emergency boolean DEFAULT true,
  rating decimal DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Ambulances table
CREATE TABLE IF NOT EXISTS ambulances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_number text UNIQUE NOT NULL,
  driver_name text DEFAULT '',
  driver_phone text DEFAULT '',
  location_lat decimal DEFAULT 0,
  location_lng decimal DEFAULT 0,
  status text DEFAULT 'available' CHECK (status IN ('available', 'busy', 'offline')),
  hospital_id uuid REFERENCES hospitals(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Emergency Requests table
CREATE TABLE IF NOT EXISTS emergency_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  hospital_id uuid REFERENCES hospitals(id) ON DELETE SET NULL,
  ambulance_id uuid REFERENCES ambulances(id) ON DELETE SET NULL,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'dispatched', 'en_route', 'arrived', 'completed', 'cancelled')),
  severity text DEFAULT 'medium' CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  symptoms text[] DEFAULT ARRAY[]::text[],
  description text DEFAULT '',
  pickup_location jsonb DEFAULT '{}'::jsonb,
  estimated_arrival timestamptz,
  actual_arrival timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Chat Sessions table
CREATE TABLE IF NOT EXISTS chat_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  title text DEFAULT 'Emergency Consultation',
  status text DEFAULT 'active' CHECK (status IN ('active', 'closed')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Chat Messages table
CREATE TABLE IF NOT EXISTS chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid REFERENCES chat_sessions(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role text NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now()
);

-- Patient Vitals table
CREATE TABLE IF NOT EXISTS patient_vitals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  emergency_request_id uuid REFERENCES emergency_requests(id) ON DELETE SET NULL,
  heart_rate integer,
  blood_pressure text DEFAULT '',
  temperature decimal,
  oxygen_level integer,
  respiratory_rate integer,
  notes text DEFAULT '',
  recorded_at timestamptz DEFAULT now()
);

-- Enable Row Level Security on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE hospitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE ambulances ENABLE ROW LEVEL SECURITY;
ALTER TABLE emergency_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_vitals ENABLE ROW LEVEL SECURITY;

-- Profiles policies
CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = id);

-- Hospitals policies (public read for emergency access)
CREATE POLICY "Anyone can view hospitals"
  ON hospitals FOR SELECT
  TO authenticated, anon
  USING (true);

CREATE POLICY "Only admin can insert hospitals"
  ON hospitals FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Only admin can update hospitals"
  ON hospitals FOR UPDATE
  TO authenticated
  USING (true);

-- Ambulances policies (public read for tracking)
CREATE POLICY "Anyone can view ambulances"
  ON ambulances FOR SELECT
  TO authenticated, anon
  USING (true);

CREATE POLICY "Only admin can insert ambulances"
  ON ambulances FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Only admin can update ambulances"
  ON ambulances FOR UPDATE
  TO authenticated
  USING (true);

-- Emergency Requests policies
CREATE POLICY "Users can view own emergency requests"
  ON emergency_requests FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create emergency requests"
  ON emergency_requests FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own emergency requests"
  ON emergency_requests FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id);

-- Chat Sessions policies
CREATE POLICY "Users can view own chat sessions"
  ON chat_sessions FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create chat sessions"
  ON chat_sessions FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own chat sessions"
  ON chat_sessions FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id);

-- Chat Messages policies
CREATE POLICY "Users can view own chat messages"
  ON chat_messages FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create chat messages"
  ON chat_messages FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Patient Vitals policies
CREATE POLICY "Users can view own vitals"
  ON patient_vitals FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own vitals"
  ON patient_vitals FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON profiles(id);
CREATE INDEX IF NOT EXISTS idx_hospitals_location ON hospitals(location_lat, location_lng);
CREATE INDEX IF NOT EXISTS idx_ambulances_location ON ambulances(location_lat, location_lng);
CREATE INDEX IF NOT EXISTS idx_ambulances_status ON ambulances(status);
CREATE INDEX IF NOT EXISTS idx_emergency_requests_user ON emergency_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_emergency_requests_status ON emergency_requests(status);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_user ON chat_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_patient_vitals_user ON patient_vitals(user_id);